[package]
name = "day1"
version = "0.1.0"
authors = ["Jonathan Keller <19418817+NobodyNada@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
